### ISSUE TITLE
There seems to be sth wrong with my server

### ISSUE THREAD

**Issue by HOOCCOOH** [cyberkitsune/PSO2Proxy#143]
I tried to connect my own server and it show like this

[ShipProxy] Opened listen socked on port 12136 for new ship.
[BlockCache] Cached new block for ship 12100, Holding onto it for 5 minutes...
[ShipProxy] Opened listen socked on port 12119 for new ship.
[BlockCache] Cached new block for ship 12100, Holding onto it for 5 minutes...
[ShipProxy] New client connected!
[ShipProxy] Client is looking for block on port 12119...
Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/python/log.py", line 73, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
    why = selectable.doRead()
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/internet/tcp.py", line 1070, in doRead
    protocol.makeConnection(transport)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/protocol.py", line 481, in makeConnection
    self.connectionMade()
  File "/root/PSO2Proxy/proxy/ShipProxy.py", line 189, in connectionMade
    blocks.blockList[port][0], port, blocks.blockList[port][1]))
exceptions.UnicodeEncodeError: 'ascii' codec can't encode characters in position 71-80: ordinal not in range(128)

BTW I use Ubuntu 14.04

**Comment by alama** [comment]
It looks like you did not enable UTF-8 support on your server

**Comment by HOOCCOOH** [comment]
root@default:~/PSO2Proxy/proxy# dpkg-reconfigure locales
Generating locales...
  en_US.UTF-8... up-to-date
Generation complete.
root@default:~/PSO2Proxy/proxy#

it just show thing above

**Comment by alama** [comment]
there 2 half to this: UTF-8 support in libc and UTF-8 support in the SSH client/terminal, it seems the 2nd half is not true, what are you using?

**Comment by HOOCCOOH** [comment]
I use PuTTY

**Comment by alama** [comment]
http://thegreyblog.blogspot.com/2009/08/configuring-putty-to-use-utf-8.html

**Comment by HOOCCOOH** [comment]
Still not working 
Do I need to reboot my server?
[ShipProxy] Client is looking for block on port 12140...
Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/python/log.py", line 73, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
    why = selectable.doRead()
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/internet/tcp.py", line 1070, in doRead
    protocol.makeConnection(transport)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/protocol.py", line 481, in makeConnection
    self.connectionMade()
  File "/root/PSO2Proxy/proxy/ShipProxy.py", line 189, in connectionMade
    blocks.blockList[port][0], port, blocks.blockList[port][1]))
exceptions.UnicodeEncodeError: 'ascii' codec can't encode characters in position 71-80: ordinal not in range(128)

**Comment by alama** [comment]
let see...
Ubuntu 14.04, what arch? and output of 'dpkg -l python-twisted python-crypto python-yaml python-faulthandler python-pip openssl git'

**Comment by HOOCCOOH** [comment]
root@default:~# dpkg -l python-twisted python-crypto python-yaml python-faulthandler python-pip openssl git
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version      Architecture Description
+++-==============-============-============-=================================
ii  git            1:1.9.1-1ubu i386         fast, scalable, distributed revis
ii  openssl        1.0.1f-1ubun i386         Secure Sockets Layer toolkit - cr
ii  python-crypto  2.6.1-4build i386         cryptographic algorithms and prot
ii  python-faultha 2.0-1        i386         Display the Python backtrace on a
ii  python-pip     1.5.4-1      all          alternative Python package instal
ii  python-twisted 13.2.0-1ubun all          Event-based framework for interne
ii  python-yaml    3.10-4ubuntu i386         YAML parser and emitter for Pytho
root@default:~#

**Comment by HOOCCOOH** [comment]
root@default:~/PSO2Proxy/proxy# arch
i686
